name: Dynamic Analysis with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dynamic-analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Start the Application
      - name: Start Application
        run: |
          npm install
          nohup npm start &
          sleep 5 # Wait for the server to start
          curl -I http://127.0.0.1:3000 # Verify the server is running
        env:
          CI: true

      # Step 3: Run OWASP ZAP Baseline Scan
      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py \
            -t http://host.docker.internal:3000 \
            -r zap-report.html \
            -w zap.log
        env:
          DISPLAY: :0

      # Step 4: Print ZAP Logs
      - name: Print ZAP Logs
        run: cat zap.log

      # Step 5: Upload the ZAP Report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html